### ISSUE TITLE
Text widget not displayed

### ISSUE THREAD

**Issue by prsmendonca** [microsoft/vscode-jupyter-ipywidgets#6] opened 2022-09-26 18:26 UTC
The displaying in vscode of a text widget from ipywidgets is not working for me. In my first cell I have

````
import IPython
import ipywidgets
import sys

print(IPython.__version__)
print(ipywidgets.__version__)
print(sys.version)
````

and the output is

8.5.0
8.0.2
3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]

In the next cell I have.

````
text = ipywidgets.Text(value="a")
IPython.display.display(text)
````

and that doesn't produce any output. Mimetype for that cell's output is "application/vnd.jupyter.widget-view+json". For reference, the cell

````
radiobuttons = ipywidgets.RadioButtons(options=["b", "c"], disabled=False)
IPython.display.display(radiobuttons)
````

produces the desired output, i.e., a pair of clickable radio buttons labelled "a" and "b". I've tried the same code with Python 3.8.13, same effect, and different orders for the cells, also same effect. My vscode is

Version: 1.72.0-insider (user setup)
Commit: 831678f718c8e998adc40d4854d9d35d9586a09f
Date: 2022-09-26T09:36:17.515Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.25201
Sandboxed: Yes

Any clues? Thanks!

**Comment by DonJayamanne** [comment] 2022-09-26 21:45
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/8552

**Closed as completed by DonJayamanne** 2022-09-26 21:45 UTC
